include classpath("application.conf")

queues {
  carrier-risk-arrivals-dlq {}

  carrier-risk-arrivals {
    defaultVisibilityTimeout = 3600 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = carrier-risk-arrivals-dlq
      maxReceiveCount = 5
    }
  }
}
